apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-dxns
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-zxdk-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-dxns@sha256:872945a3907587f10b8823193d8be07611e4f7d6c5bae769c0a9ced20730d79c
        name: my-python
        resources: {}
status: {}
